openapi: 3.0.3
info:
  title: Dokumen API Web Informasi Wisata Bandung Oleh Backend Developer Akbar
  description: Dokumentasi API Informasi Wisata Bandung (IWB)
  termsOfService: https://github.com/InformasiwisataBandung/swagger
  contact:
    email: salmanakbartafisa@gmail.com
  license:
    name: Informasi Wisata Bandung 
    url:  https://pkg.go.dev/github.com/InformasiwisataBandung/BackendGO
  version: 1.0.11
externalDocs:
  description: Repositori Google Cloud Function !         
  url: github.com/InformasiwisataBandung/BackendGO
servers:
  - url: https://asia-southeast2-bustling-walker-340203.cloudfunctions.net
tags:
  - name: Authorization
    description: Signup Akun dan Authorization
    externalDocs:
      description: Deskripsi dan Kode Program
      url: https://pkg.go.dev/github.com/InformasiwisataBandung/BackendGO#Registrasi
  - name: User
    description: Create read update delete user
    externalDocs:
      description: Deskripsi dan Kode Program
      url: 
  - name: Wisata
    description: Create read update delete Wisata
    externalDocs:
      description: Deskripsi dan Kode Program
      url:   https://pkg.go.dev/github.com/InformasiwisataBandung/BackendGO#CreateWisata
  - name: Komentar
    description: Komentar
    externalDocs:
      description: Deskripsi dan Kode Program
      url:  

paths:
  # ------------------------- Authorization
  /function-1SIGNAUTHWA:
    post:
      tags:
        - Authorization
      summary: Registrasi
      description: Membuat akun user dengan password terbcypt
      operationId: MembuatUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Berhasil'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - token:
            - write:apiKey
            - read:apiKey

  /SIgnin-1Signin-1:
    post:
      tags:
        - Authorization
      summary: Login
      description: Input Username dan Password
      operationId: MembuatTokenUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatLoginUser'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BerhasilDapetToken'
        '400':
          description: failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gagal'
      security:
        - token:
            - write:apiKey
            - read:apiKey

  /OtorisasiFIx:
    get:
      tags:
        - Authorization
      summary: Authorization
      description: Authorization
      operationId: Authorization
      requestBody:
        content:
          application/json:
      responses:
        '200':
          description: Successful decoding of the token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulDecodeAuthorization'
        '400':
          description: Failed decoding of the token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedDecodeAuthorization'
      security:
        - token:
            - write:apiKey
            - read:apiKey
 # ------------------------- Wisata
  /CreateWIsataToken1:
    post:
      tags:
        - Wisata
      summary: Membuat tempat wisata baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WisataData'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      security:
        - token:
            - write:apiKey
            - read:apiKey
  /7ReadWisata:
    get:
      tags :
       - Wisata
      summary: Membaca data tempat wisata
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object  # Sesuaikan dengan struktur objek tempat wisata
                      properties:
                        nama:
                          type: string
                        jenis:
                          type: string
                        deskripsi:
                          type: string
                        lokasi:
                          type: object
                          properties:
                            type:
                              type: string
                            coordinates:
                              type: array
                              items:
                                type: number
                                format: double
                          required:
                            - type
                            - coordinates
                        alamat:
                          type: string
                        gambar:
                          type: string
                        rating:
                          type: number
                          format: double
  /UpdateWisata:
     post:
      tags:
        - Wisata
      summary: Memperbarui informasi wisata
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WisataInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WisataResponse'
      security:
        - token:
            - write:apiKey
            - read:apiKey
components:
  schemas:
    # ----------------------------- Schema struct User
    FormatUser:
      example:
        no_whatsapp: "6281xxx"
        username: "Budi"
        password: "AnakIT"
        role: "admin"
    FormatLoginUser:
      example:
        username: "Budi"
        password: "AnakIT"
    FormatUsernameUser:
      example:
        username: "contoh"
    # ----------------------------- Schema struct Wisata
    WisataData:
      type: object
      properties:
        nama:
          type: string
        jenis:
          type: string
        deskripsi:
          type: string
        lokasi:
          type: object
          properties:
            type:
              type: string
              enum:
                - Point
            coordinates:
              type: array
              items:
                type: number
                format: float
        alamat:
          type: string
        gambar:
          type: string
        rating:
          type: number
          format: float
    WisataInput:
      type: object
      properties:
        nama:
          type: string
        jenis:
          type: string
        deskripsi:
          type: string
        lokasi:
          type: object
          properties:
            type:
              type: string
            coordinates:
              type: array
              items:
                type: number
                format: double
          required:
            - type
            - coordinates
        alamat:
          type: string
        gambar:
          type: string
        rating:
          type: number
          format: double
    WisataResponse:
      type: object
      properties:
        message:
          type: string
        updatedData:
          $ref: '#/components/schemas/WisataInput'
    # ----------------------------- Schema struct Komentar
    
    # ----------------------------- Schema response
    Response:
      type: object
      properties:
        Status:
          type: boolean
        Message:
          type: string
    BerhasilDapetToken:
      example:
        status: true
        message: "berhasil login"
        token: "v4.public.eyJleHAiOiIyMDIzLTExLTMwVDA4OjUwOjE2WiIsImlhdCI6IjIwMjMtMTEtMzBUMDY6NTA6MTZaIiwibmFtZSI6Iklicm9oaW0gTXViYXJvayIsIm5iZiI6IjIwMjMtMTEtMzBUMDY6NTA6MTZaIiwicm9sZSI6ImFkbWluIiwidXNlcm5hbWUiOiJpYnJvaGltIn1438aT4CYjh1m4w1NLuW-ebGKL6mvztDPsh2ZKLy8DKBjKh4KZEI4ZQAboqKTLhGzQ930yKVAEMKSAvMHhqMQH"
    BerhasilGetAllUser:
      example:
        - name: "Contoh1"
          email: "contoh1@gmail.com"
          no_whatsapp: "6281271720763"
          username: "contoh1"
          password: "hashed password"
          role: "admin"
        - name: "Contoh2"
          email: "contoh2@gmail.com"
          no_whatsapp: "6281271720763"
          username: "contoh2"
          password: "hashed password"
          role: "author"
    BerhasilGetOneUser:
      example:
        name: "Contoh"
        email: "contoh@gmail.com"
        no_whatsapp: "6281271720763"
        username: "contoh"
        password: "hashed password"
        role: "admin"
    BerhasilGetAllBerita:
      example:
        - id: "contoh1"
          kategori: "politic"
          judul: "contoh1"
          preview: "ini adalah contoh politic"
          konten:
            paragraf1: "contoh1"
            paragraf2: "contoh1"
            paragraf3: "contoh1"
            paragraf4: "contoh1"
            paragraf5: "contoh1"
            paragraf6: "contoh1"
            paragraf7: "contoh1"
            paragraf8: "contoh1"
            paragraf9: "contoh1"
            paragraf10: "contoh1"
          penulis: "contoh1"
          sumber: "contoh1.com"
          image: "google.com"
          waktu: "Monday, 2 January 2006 15:04 WIB"
        - id: "contoh2"
          kategori: "politic"
          judul: "contoh2"
          preview: "ini adalah contoh politic"
          konten:
            paragraf1: "contoh2"
            paragraf2: "contoh2"
            paragraf3: "contoh2"
            paragraf4: "contoh2"
            paragraf5: "contoh2"
            paragraf6: "contoh2"
            paragraf7: "contoh2"
            paragraf8: "contoh2"
            paragraf9: "contoh2"
            paragraf10: "contoh2"
          penulis: "contoh2"
          sumber: "contoh2.com"
          image: "google.com"
          waktu: "Monday, 2 January 2006 15:04 WIB"
    BerhasilGetOneBerita:
      example:
        id: "contoh"
        kategori: "politic"
        judul: "contoh"
        preview: "ini adalah contoh politic"
        konten:
          paragraf1: "contoh"
          paragraf2: "contoh"
          paragraf3: "contoh"
          paragraf4: "contoh"
          paragraf5: "contoh"
          paragraf6: "contoh"
          paragraf7: "contoh"
          paragraf8: "contoh"
          paragraf9: "contoh"
          paragraf10: "contoh"
        penulis: "contoh"
        sumber: "contoh.com"
        image: "google.com"
        waktu: "Monday, 2 January 2006 15:04 WIB"
    BerhasilGetAllKomentar:
      example:
        - id: "contoh1"
          id_berita: "contohberita"
          name: "contoh1"
          tanggal: "January 2, 2006"
          komentar: "ini adalah contoh komentar"
        - id: "contoh2"
          id_berita: "contohberita"
          name: "contoh2"
          tanggal: "January 2, 2006"
          komentar: "ini adalah contoh komentar"
    BerhasilGetOneKomentar:
      example:
        id: "contoh"
        id_berita: "contohberita"
        name: "contoh"
        tanggal: "January 2, 2006"
        komentar: "ini adalah contoh komentar"
    Berhasil:
      example:
        status: true
        message: "petunjuk apa yang berhasil"
    Gagal:
      example:
        status: false
        message: "petunjuk dimana salahnya"
    SuccessfulDecodeAuthorization:
      example:
        status: true
        data:
          no_whatsapp: ""
          username: "Ibrohim Mubarok"
          password: ""
          role: "admin"
        message: "berhasil decode token"
    FailedDecodeAuthorization:
      example:
        status: false
        data:
          no_whatsapp: ""
          username: ""
          password: ""
        message: "header login tidak ditemukan"
  requestBodies:
    AuthReq:
      description: Request Authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Auth'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AuthResponse'
  securitySchemes:
    token:
      type: apiKey
      name: token
      in: header
